from __future__ import annotations


# Display order is part of the seed data, not parser code. Operators can change it in the UI.
DEFAULT_CATEGORIES = [
    ("收入", "薪酬", "工资", "income"),
    ("收入", "补贴与退款", "补贴", "income"),
    ("收入", "投资与利息", "利息", "income"),
    ("收入", "个人转入", "朋友与家人", "income"),
    ("收入", "其他收入", "待分类", "income"),
    ("固定支出", "住房", "房租与物业", "expense"),
    ("固定支出", "账单与通信", "水电网费", "expense"),
    ("固定支出", "保险", "保险费", "expense"),
    ("固定支出", "订阅", "订阅服务", "expense"),
    ("固定支出", "固定车辆成本", "车贷与车险", "expense"),
    ("可变支出", "食品日用", "超市", "expense"),
    ("可变支出", "餐饮", "外食与外卖", "expense"),
    ("可变支出", "购物与服饰", "购物", "expense"),
    ("可变支出", "交通", "公共交通", "expense"),
    ("可变支出", "交通", "油费与停车", "expense"),
    ("可变支出", "医疗健康", "医疗", "expense"),
    ("可变支出", "宠物", "宠物支出", "expense"),
    ("可变支出", "娱乐", "娱乐", "expense"),
    ("可变支出", "旅行", "旅行", "expense"),
    ("可变支出", "教育", "教育", "expense"),
    ("可变支出", "政府与手续费", "政府缴费", "expense"),
    ("可变支出", "社交与第三方转出", "转给他人", "expense"),
    ("转账与调整", "自有账户转账", "内部转账", "excluded"),
    ("转账与调整", "冲正", "冲正交易", "excluded"),
    ("转账与调整", "待复核", "待分类", "excluded"),
    ("投资", "现金流", "入金", "investment"),
    ("投资", "证券交易", "买入", "investment"),
    ("投资", "证券交易", "卖出", "investment"),
    ("投资", "收益与费用", "分红", "investment"),
    ("投资", "收益与费用", "费用", "investment"),
]
